[
  {
    "student_id": "8",
    "first_name": "Kippie",
    "last_name": "Toyne",
    "age": "19",
    "email": "ktoyne7@tripod.com",
    "country": "Czech Republic",
    "postal_code": "509 01",
    "favorite_color": "green",
    "enrollment_date": "12/6/2020",
    "gpa": "3.0",
    "external_system": "internal"
  },
  {
    "student_id": "14",
    "first_name": "Ari",
    "last_name": "Voice",
    "age": "22",
    "email": "avoiced@diigo.com",
    "country": "Philippines",
    "postal_code": "4703",
    "favorite_color": "green",
    "enrollment_date": "6/28/2021",
    "gpa": "3.89",
    "external_system": "internal"
  },
  {
    "student_id": "15",
    "first_name": "Chickie",
    "last_name": "Huortic",
    "age": "18",
    "email": "chuortice@t.co",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "11/13/2021",
    "gpa": "3.5",
    "external_system": "internal"
  },
  {
    "student_id": "22",
    "first_name": "Rea",
    "last_name": "Brame",
    "age": "18",
    "email": "rbramel@smh.com.au",
    "country": "Croatia",
    "postal_code": "10430",
    "favorite_color": "red",
    "enrollment_date": "5/10/2020",
    "gpa": "0.53",
    "external_system": "internal"
  },
  {
    "student_id": "23",
    "first_name": "Hewe",
    "last_name": "Harvard",
    "age": "21",
    "email": "hharvardm@wunderground.com",
    "country": "Russia",
    "postal_code": "243126",
    "favorite_color": "green",
    "enrollment_date": "9/10/2022",
    "gpa": "2.84",
    "external_system": "internal"
  },
  {
    "student_id": "24",
    "first_name": "Erik",
    "last_name": "Beaby",
    "age": "20",
    "email": "ebeabyn@creativecommons.org",
    "country": "Sweden",
    "postal_code": "171 43",
    "favorite_color": "blue",
    "enrollment_date": "6/14/2022",
    "gpa": "1.36",
    "external_system": "internal"
  },
  {
    "student_id": "25",
    "first_name": "Emelyne",
    "last_name": "McElory",
    "age": "23",
    "email": "emceloryo@scribd.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/24/2021",
    "gpa": "3.89",
    "external_system": "internal"
  },
  {
    "student_id": "32",
    "first_name": "Adrien",
    "last_name": "Rubbert",
    "age": "19",
    "email": "arubbertv@businessweek.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/20/2020",
    "gpa": "2.8",
    "external_system": "internal"
  },
  {
    "student_id": "33",
    "first_name": "Tod",
    "last_name": "Ailward",
    "age": "25",
    "email": "tailwardw@wp.com",
    "country": "Poland",
    "postal_code": "83-020",
    "favorite_color": "red",
    "enrollment_date": "11/17/2020",
    "gpa": "1.9",
    "external_system": "internal"
  },
  {
    "student_id": "34",
    "first_name": "Mirabelle",
    "last_name": "O'Dowling",
    "age": "21",
    "email": "modowlingx@rakuten.co.jp",
    "country": "France",
    "postal_code": "62025 CEDEX",
    "favorite_color": "red",
    "enrollment_date": "3/5/2020",
    "gpa": "1.07",
    "external_system": "internal"
  },
  {
    "student_id": "38",
    "first_name": "Shirleen",
    "last_name": "Antosch",
    "age": "20",
    "email": "santosch11@soup.io",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "8/8/2022",
    "gpa": "3.68",
    "external_system": "internal"
  },
  {
    "student_id": "39",
    "first_name": "Janessa",
    "last_name": "Peggram",
    "age": "20",
    "email": "jpeggram12@typepad.com",
    "country": "Macedonia",
    "postal_code": "1040",
    "favorite_color": "blue",
    "enrollment_date": "6/20/2020",
    "gpa": "2.23",
    "external_system": "internal"
  },
  {
    "student_id": "42",
    "first_name": "Isabelle",
    "last_name": "Jakoub",
    "age": "25",
    "email": "ijakoub15@who.int",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/12/2021",
    "gpa": "3.33",
    "external_system": "internal"
  },
  {
    "student_id": "48",
    "first_name": "Amerigo",
    "last_name": "Hatherley",
    "age": "22",
    "email": "ahatherley1b@google.co.jp",
    "country": "Bangladesh",
    "postal_code": "1938",
    "favorite_color": "red",
    "enrollment_date": "1/9/2020",
    "gpa": "1.46",
    "external_system": "internal"
  },
  {
    "student_id": "49",
    "first_name": "Skip",
    "last_name": "Rosnau",
    "age": "19",
    "email": "srosnau1c@vk.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/17/2021",
    "gpa": "3.16",
    "external_system": "internal"
  },
  {
    "student_id": "51",
    "first_name": "Clarey",
    "last_name": "Jakubowicz",
    "age": "21",
    "email": "cjakubowicz1e@cocolog-nifty.com",
    "country": "Nepal",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/25/2020",
    "gpa": "1.22",
    "external_system": "internal"
  },
  {
    "student_id": "55",
    "first_name": "Roxine",
    "last_name": "Strongitharm",
    "age": "25",
    "email": "rstrongitharm1i@tripod.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "12/27/2022",
    "gpa": "2.25",
    "external_system": "internal"
  },
  {
    "student_id": "56",
    "first_name": "Marietta",
    "last_name": "Rabbatts",
    "age": "21",
    "email": "mrabbatts1j@dropbox.com",
    "country": "Thailand",
    "postal_code": "20140",
    "favorite_color": "red",
    "enrollment_date": "1/20/2020",
    "gpa": "0.42",
    "external_system": "internal"
  },
  {
    "student_id": "58",
    "first_name": "Gerick",
    "last_name": "Skingley",
    "age": "19",
    "email": "gskingley1l@auda.org.au",
    "country": "Philippines",
    "postal_code": "2706",
    "favorite_color": "red",
    "enrollment_date": "5/8/2020",
    "gpa": "2.36",
    "external_system": "internal"
  },
  {
    "student_id": "64",
    "first_name": "Garwood",
    "last_name": "Jollie",
    "age": "19",
    "email": "gjollie1r@nifty.com",
    "country": "Portugal",
    "postal_code": "4960-349",
    "favorite_color": "red",
    "enrollment_date": "4/18/2022",
    "gpa": "2.63",
    "external_system": "internal"
  },
  {
    "student_id": "70",
    "first_name": "Else",
    "last_name": "Vergine",
    "age": "19",
    "email": "evergine1x@booking.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/19/2020",
    "gpa": "1.54",
    "external_system": "internal"
  },
  {
    "student_id": "71",
    "first_name": "Ermengarde",
    "last_name": "Hasted",
    "age": "23",
    "email": "ehasted1y@latimes.com",
    "country": "Ethiopia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "9/5/2021",
    "gpa": "1.02",
    "external_system": "internal"
  },
  {
    "student_id": "73",
    "first_name": "Deborah",
    "last_name": "Vasilischev",
    "age": "24",
    "email": "dvasilischev20@lulu.com",
    "country": "Russia",
    "postal_code": "649154",
    "favorite_color": "blue",
    "enrollment_date": "10/24/2021",
    "gpa": "3.22",
    "external_system": "internal"
  },
  {
    "student_id": "78",
    "first_name": "Abram",
    "last_name": "Marr",
    "age": "19",
    "email": "amarr25@bloglines.com",
    "country": "Sweden",
    "postal_code": "111 20",
    "favorite_color": "red",
    "enrollment_date": "12/21/2020",
    "gpa": "0.95",
    "external_system": "internal"
  },
  {
    "student_id": "81",
    "first_name": "Fey",
    "last_name": "Titchmarsh",
    "age": "22",
    "email": "ftitchmarsh28@umich.edu",
    "country": "Papua New Guinea",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "9/11/2020",
    "gpa": "2.95",
    "external_system": "internal"
  },
  {
    "student_id": "86",
    "first_name": "Klaus",
    "last_name": "Candwell",
    "age": "18",
    "email": "kcandwell2d@foxnews.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "3/8/2022",
    "gpa": "1.95",
    "external_system": "internal"
  },
  {
    "student_id": "89",
    "first_name": "Suzy",
    "last_name": "Fishpond",
    "age": "20",
    "email": "sfishpond2g@hud.gov",
    "country": "Norway",
    "postal_code": "7712",
    "favorite_color": "blue",
    "enrollment_date": "3/2/2020",
    "gpa": "2.21",
    "external_system": "internal"
  },
  {
    "student_id": "93",
    "first_name": "Willi",
    "last_name": "Moyes",
    "age": "24",
    "email": "wmoyes2k@google.co.jp",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "3/8/2022",
    "gpa": "2.13",
    "external_system": "internal"
  },
  {
    "student_id": "94",
    "first_name": "Gilligan",
    "last_name": "Glaysher",
    "age": "19",
    "email": "gglaysher2l@infoseek.co.jp",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "11/13/2021",
    "gpa": "2.7",
    "external_system": "internal"
  },
  {
    "student_id": "95",
    "first_name": "Harper",
    "last_name": "Whitten",
    "age": "21",
    "email": "hwhitten2m@nytimes.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "12/15/2022",
    "gpa": "2.79",
    "external_system": "internal"
  },
  {
    "student_id": "98",
    "first_name": "Myriam",
    "last_name": "Kornel",
    "age": "22",
    "email": "mkornel2p@people.com.cn",
    "country": "Mongolia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "1/25/2021",
    "gpa": "3.22",
    "external_system": "internal"
  },
  {
    "student_id": "100",
    "first_name": "Avrom",
    "last_name": "Brunsden",
    "age": "22",
    "email": "abrunsden2r@utexas.edu",
    "country": "Philippines",
    "postal_code": "6546",
    "favorite_color": "blue",
    "enrollment_date": "2/16/2021",
    "gpa": "0.35",
    "external_system": "internal"
  },
  {
    "student_id": "107",
    "first_name": "Merilyn",
    "last_name": "Winger",
    "age": "22",
    "email": "mwinger2y@purevolume.com",
    "country": "Colombia",
    "postal_code": "052027",
    "favorite_color": "blue",
    "enrollment_date": "10/24/2020",
    "gpa": "1.42",
    "external_system": "internal"
  },
  {
    "student_id": "111",
    "first_name": "Ingamar",
    "last_name": "Kennler",
    "age": "24",
    "email": "ikennler32@vk.com",
    "country": "Malawi",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "2/28/2022",
    "gpa": "2.69",
    "external_system": "internal"
  },
  {
    "student_id": "121",
    "first_name": "Jordon",
    "last_name": "Elles",
    "age": "21",
    "email": "jelles3c@mail.ru",
    "country": "Kyrgyzstan",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "1/29/2022",
    "gpa": "1.93",
    "external_system": "internal"
  },
  {
    "student_id": "127",
    "first_name": "Lara",
    "last_name": "Velti",
    "age": "23",
    "email": "lvelti3i@cam.ac.uk",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "1/23/2021",
    "gpa": "2.8",
    "external_system": "internal"
  },
  {
    "student_id": "129",
    "first_name": "Britte",
    "last_name": "Ellif",
    "age": "18",
    "email": "bellif3k@loc.gov",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "3/7/2021",
    "gpa": "2.34",
    "external_system": "internal"
  },
  {
    "student_id": "130",
    "first_name": "Rakel",
    "last_name": "Meriton",
    "age": "18",
    "email": "rmeriton3l@dailymotion.com",
    "country": "Malaysia",
    "postal_code": "30200",
    "favorite_color": "blue",
    "enrollment_date": "8/25/2022",
    "gpa": "3.8",
    "external_system": "internal"
  },
  {
    "student_id": "134",
    "first_name": "Elwira",
    "last_name": "Peartree",
    "age": "23",
    "email": "epeartree3p@fotki.com",
    "country": "Peru",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "11/26/2021",
    "gpa": "1.62",
    "external_system": "internal"
  },
  {
    "student_id": "135",
    "first_name": "Kyle",
    "last_name": "Polhill",
    "age": "23",
    "email": "kpolhill3q@blinklist.com",
    "country": "Comoros",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/13/2020",
    "gpa": "2.65",
    "external_system": "internal"
  },
  {
    "student_id": "137",
    "first_name": "Leshia",
    "last_name": "Le Galle",
    "age": "22",
    "email": "llegalle3s@tmall.com",
    "country": "Argentina",
    "postal_code": "4124",
    "favorite_color": "red",
    "enrollment_date": "2/3/2020",
    "gpa": "1.08",
    "external_system": "internal"
  },
  {
    "student_id": "140",
    "first_name": "Karel",
    "last_name": "Brussels",
    "age": "23",
    "email": "kbrussels3v@apple.com",
    "country": "Czech Republic",
    "postal_code": "595 01",
    "favorite_color": "green",
    "enrollment_date": "2/8/2021",
    "gpa": "1.14",
    "external_system": "internal"
  },
  {
    "student_id": "141",
    "first_name": "Ardene",
    "last_name": "Brise",
    "age": "20",
    "email": "abrise3w@feedburner.com",
    "country": "Sweden",
    "postal_code": "124 64",
    "favorite_color": "red",
    "enrollment_date": "6/14/2022",
    "gpa": "0.98",
    "external_system": "internal"
  },
  {
    "student_id": "146",
    "first_name": "Juana",
    "last_name": "Noury",
    "age": "23",
    "email": "jnoury41@addtoany.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/10/2021",
    "gpa": "3.9",
    "external_system": "internal"
  },
  {
    "student_id": "148",
    "first_name": "Fulvia",
    "last_name": "Standon",
    "age": "20",
    "email": "fstandon43@dailymotion.com",
    "country": "Brazil",
    "postal_code": "63580-000",
    "favorite_color": "green",
    "enrollment_date": "5/22/2021",
    "gpa": "1.06",
    "external_system": "internal"
  },
  {
    "student_id": "149",
    "first_name": "Joy",
    "last_name": "Loughlin",
    "age": "25",
    "email": "jloughlin44@oracle.com",
    "country": "Portugal",
    "postal_code": "2870-005",
    "favorite_color": "blue",
    "enrollment_date": "5/11/2021",
    "gpa": "1.49",
    "external_system": "internal"
  },
  {
    "student_id": "150",
    "first_name": "Inge",
    "last_name": "Palphreyman",
    "age": "22",
    "email": "ipalphreyman45@jalbum.net",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "7/11/2022",
    "gpa": "3.09",
    "external_system": "internal"
  },
  {
    "student_id": "163",
    "first_name": "Greer",
    "last_name": "O'Daly",
    "age": "18",
    "email": "godaly4i@tmall.com",
    "country": "Slovenia",
    "postal_code": "2325",
    "favorite_color": "green",
    "enrollment_date": "11/5/2021",
    "gpa": "2.26",
    "external_system": "internal"
  },
  {
    "student_id": "168",
    "first_name": "Kellia",
    "last_name": "Quinney",
    "age": "23",
    "email": "kquinney4n@cafepress.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "5/18/2020",
    "gpa": "2.33",
    "external_system": "internal"
  },
  {
    "student_id": "172",
    "first_name": "Lila",
    "last_name": "Campelli",
    "age": "20",
    "email": "lcampelli4r@pbs.org",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/31/2020",
    "gpa": "1.62",
    "external_system": "internal"
  },
  {
    "student_id": "176",
    "first_name": "Finn",
    "last_name": "Cuppleditch",
    "age": "21",
    "email": "fcuppleditch4v@newsvine.com",
    "country": "Ecuador",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "10/17/2021",
    "gpa": "0.5",
    "external_system": "internal"
  },
  {
    "student_id": "181",
    "first_name": "Ryun",
    "last_name": "Stegel",
    "age": "18",
    "email": "rstegel50@mail.ru",
    "country": "Argentina",
    "postal_code": "6311",
    "favorite_color": "green",
    "enrollment_date": "1/4/2021",
    "gpa": "2.05",
    "external_system": "internal"
  },
  {
    "student_id": "183",
    "first_name": "Eldon",
    "last_name": "Roscamps",
    "age": "22",
    "email": "eroscamps52@wired.com",
    "country": "Colombia",
    "postal_code": "056077",
    "favorite_color": "red",
    "enrollment_date": "5/24/2020",
    "gpa": "3.47",
    "external_system": "internal"
  },
  {
    "student_id": "184",
    "first_name": "Renado",
    "last_name": "Jendrassik",
    "age": "24",
    "email": "rjendrassik53@shop-pro.jp",
    "country": "Poland",
    "postal_code": "18-411",
    "favorite_color": "blue",
    "enrollment_date": "8/4/2020",
    "gpa": "3.74",
    "external_system": "internal"
  },
  {
    "student_id": "185",
    "first_name": "Etan",
    "last_name": "Enrique",
    "age": "24",
    "email": "eenrique54@blog.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "7/23/2022",
    "gpa": "3.2",
    "external_system": "internal"
  },
  {
    "student_id": "192",
    "first_name": "Demetris",
    "last_name": "Chavey",
    "age": "20",
    "email": "dchavey5b@google.cn",
    "country": "Sweden",
    "postal_code": "590 14",
    "favorite_color": "blue",
    "enrollment_date": "9/28/2020",
    "gpa": "3.09",
    "external_system": "internal"
  },
  {
    "student_id": "199",
    "first_name": "Fran",
    "last_name": "Scampion",
    "age": "25",
    "email": "fscampion5i@flavors.me",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "8/28/2022",
    "gpa": "0.89",
    "external_system": "internal"
  },
  {
    "student_id": "203",
    "first_name": "Gilburt",
    "last_name": "Noirel",
    "age": "20",
    "email": "gnoirel5m@simplemachines.org",
    "country": "Portugal",
    "postal_code": "2785-019",
    "favorite_color": "green",
    "enrollment_date": "3/12/2020",
    "gpa": "1.96",
    "external_system": "internal"
  },
  {
    "student_id": "210",
    "first_name": "Ellie",
    "last_name": "Matterdace",
    "age": "19",
    "email": "ematterdace5t@nyu.edu",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "9/19/2021",
    "gpa": "2.71",
    "external_system": "internal"
  },
  {
    "student_id": "214",
    "first_name": "Rea",
    "last_name": "Kiendl",
    "age": "20",
    "email": "rkiendl5x@xinhuanet.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "8/21/2022",
    "gpa": "3.99",
    "external_system": "internal"
  },
  {
    "student_id": "215",
    "first_name": "Garrard",
    "last_name": "Buggs",
    "age": "20",
    "email": "gbuggs5y@aol.com",
    "country": "Thailand",
    "postal_code": "45220",
    "favorite_color": "red",
    "enrollment_date": "1/7/2021",
    "gpa": "0.36",
    "external_system": "internal"
  },
  {
    "student_id": "216",
    "first_name": "Ginnie",
    "last_name": "Cumberlidge",
    "age": "19",
    "email": "gcumberlidge5z@phoca.cz",
    "country": "Bosnia and Herzegovina",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "8/24/2022",
    "gpa": "2.5",
    "external_system": "internal"
  },
  {
    "student_id": "218",
    "first_name": "Nessi",
    "last_name": "Sinnatt",
    "age": "24",
    "email": "nsinnatt61@cafepress.com",
    "country": "Thailand",
    "postal_code": "10500",
    "favorite_color": "red",
    "enrollment_date": "6/19/2022",
    "gpa": "1.77",
    "external_system": "internal"
  },
  {
    "student_id": "226",
    "first_name": "Hillyer",
    "last_name": "Kondratenko",
    "age": "21",
    "email": "hkondratenko69@unesco.org",
    "country": "Dominican Republic",
    "postal_code": "10412",
    "favorite_color": "red",
    "enrollment_date": "2/17/2020",
    "gpa": "3.26",
    "external_system": "internal"
  },
  {
    "student_id": "232",
    "first_name": "Quentin",
    "last_name": "Bleasby",
    "age": "19",
    "email": "qbleasby6f@qq.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "3/25/2021",
    "gpa": "3.68",
    "external_system": "internal"
  },
  {
    "student_id": "233",
    "first_name": "Kerrin",
    "last_name": "Danieli",
    "age": "20",
    "email": "kdanieli6g@hugedomains.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "1/13/2021",
    "gpa": "3.14",
    "external_system": "internal"
  },
  {
    "student_id": "237",
    "first_name": "Renaldo",
    "last_name": "Tonge",
    "age": "18",
    "email": "rtonge6k@amazon.co.jp",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/19/2021",
    "gpa": "0.83",
    "external_system": "internal"
  },
  {
    "student_id": "241",
    "first_name": "Westbrooke",
    "last_name": "Postill",
    "age": "23",
    "email": "wpostill6o@acquirethisname.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "9/9/2021",
    "gpa": "2.69",
    "external_system": "internal"
  },
  {
    "student_id": "245",
    "first_name": "Korey",
    "last_name": "Soeiro",
    "age": "22",
    "email": "ksoeiro6s@umn.edu",
    "country": "Brazil",
    "postal_code": "08550-000",
    "favorite_color": "blue",
    "enrollment_date": "12/16/2020",
    "gpa": "0.34",
    "external_system": "internal"
  },
  {
    "student_id": "252",
    "first_name": "Kiel",
    "last_name": "Bamlett",
    "age": "18",
    "email": "kbamlett6z@cmu.edu",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "1/13/2022",
    "gpa": "3.57",
    "external_system": "internal"
  },
  {
    "student_id": "263",
    "first_name": "Duffie",
    "last_name": "Georg",
    "age": "20",
    "email": "dgeorg7a@topsy.com",
    "country": "Czech Republic",
    "postal_code": "789 01",
    "favorite_color": "red",
    "enrollment_date": "10/30/2020",
    "gpa": "1.55",
    "external_system": "internal"
  },
  {
    "student_id": "265",
    "first_name": "Ettore",
    "last_name": "Di Pietro",
    "age": "24",
    "email": "edipietro7c@indiatimes.com",
    "country": "Vietnam",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "11/5/2020",
    "gpa": "3.94",
    "external_system": "internal"
  },
  {
    "student_id": "269",
    "first_name": "Ambrosi",
    "last_name": "Worvell",
    "age": "23",
    "email": "aworvell7g@toplist.cz",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "7/21/2020",
    "gpa": "1.59",
    "external_system": "internal"
  },
  {
    "student_id": "277",
    "first_name": "Leodora",
    "last_name": "Scothorne",
    "age": "23",
    "email": "lscothorne7o@taobao.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "11/23/2020",
    "gpa": "2.18",
    "external_system": "internal"
  },
  {
    "student_id": "283",
    "first_name": "Luciana",
    "last_name": "Matterson",
    "age": "24",
    "email": "lmatterson7u@vkontakte.ru",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/31/2020",
    "gpa": "1.07",
    "external_system": "internal"
  },
  {
    "student_id": "288",
    "first_name": "Vivienne",
    "last_name": "Emons",
    "age": "21",
    "email": "vemons7z@google.co.uk",
    "country": "Macedonia",
    "postal_code": "6344",
    "favorite_color": "red",
    "enrollment_date": "8/20/2020",
    "gpa": "2.67",
    "external_system": "internal"
  },
  {
    "student_id": "289",
    "first_name": "Elonore",
    "last_name": "Laetham",
    "age": "23",
    "email": "elaetham80@oakley.com",
    "country": "Brazil",
    "postal_code": "07700-000",
    "favorite_color": "blue",
    "enrollment_date": "9/16/2022",
    "gpa": "3.43",
    "external_system": "internal"
  },
  {
    "student_id": "296",
    "first_name": "Viva",
    "last_name": "Lannin",
    "age": "23",
    "email": "vlannin87@pen.io",
    "country": "Morocco",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "6/21/2021",
    "gpa": "1.84",
    "external_system": "internal"
  },
  {
    "student_id": "297",
    "first_name": "Carole",
    "last_name": "Geraldini",
    "age": "22",
    "email": "cgeraldini88@stumbleupon.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "4/7/2022",
    "gpa": "0.1",
    "external_system": "internal"
  },
  {
    "student_id": "300",
    "first_name": "Aggy",
    "last_name": "Dunbobin",
    "age": "24",
    "email": "adunbobin8b@example.com",
    "country": "Bulgaria",
    "postal_code": "6710",
    "favorite_color": "blue",
    "enrollment_date": "12/8/2022",
    "gpa": "2.08",
    "external_system": "internal"
  },
  {
    "student_id": "307",
    "first_name": "Salomo",
    "last_name": "Zanazzi",
    "age": "22",
    "email": "szanazzi8i@europa.eu",
    "country": "Brazil",
    "postal_code": "79240-000",
    "favorite_color": "red",
    "enrollment_date": "9/11/2022",
    "gpa": "0.04",
    "external_system": "internal"
  },
  {
    "student_id": "309",
    "first_name": "Kristin",
    "last_name": "Poznanski",
    "age": "21",
    "email": "kpoznanski8k@google.pl",
    "country": "Poland",
    "postal_code": "47-470",
    "favorite_color": "red",
    "enrollment_date": "2/18/2020",
    "gpa": "0.04",
    "external_system": "internal"
  },
  {
    "student_id": "315",
    "first_name": "Maury",
    "last_name": "MacKnight",
    "age": "20",
    "email": "mmacknight8q@imgur.com",
    "country": "Argentina",
    "postal_code": "5284",
    "favorite_color": "green",
    "enrollment_date": "7/10/2020",
    "gpa": "1.26",
    "external_system": "internal"
  },
  {
    "student_id": "318",
    "first_name": "Emmery",
    "last_name": "Orsay",
    "age": "21",
    "email": "eorsay8t@youku.com",
    "country": "Yemen",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/14/2020",
    "gpa": "3.06",
    "external_system": "internal"
  },
  {
    "student_id": "321",
    "first_name": "Roosevelt",
    "last_name": "Stranks",
    "age": "19",
    "email": "rstranks8w@cbsnews.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "10/29/2020",
    "gpa": "0.6",
    "external_system": "internal"
  },
  {
    "student_id": "326",
    "first_name": "Ramona",
    "last_name": "Fernez",
    "age": "23",
    "email": "rfernez91@lulu.com",
    "country": "Philippines",
    "postal_code": "4402",
    "favorite_color": "blue",
    "enrollment_date": "2/28/2020",
    "gpa": "1.65",
    "external_system": "internal"
  },
  {
    "student_id": "334",
    "first_name": "Freddi",
    "last_name": "Ovize",
    "age": "24",
    "email": "fovize99@com.com",
    "country": "Brazil",
    "postal_code": "62500-000",
    "favorite_color": "red",
    "enrollment_date": "11/23/2020",
    "gpa": "2.79",
    "external_system": "internal"
  },
  {
    "student_id": "340",
    "first_name": "Kory",
    "last_name": "Sheards",
    "age": "25",
    "email": "ksheards9f@census.gov",
    "country": "Niger",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "7/3/2022",
    "gpa": "2.77",
    "external_system": "internal"
  },
  {
    "student_id": "342",
    "first_name": "Ida",
    "last_name": "Wheelan",
    "age": "18",
    "email": "iwheelan9h@etsy.com",
    "country": "Mexico",
    "postal_code": "30540",
    "favorite_color": "green",
    "enrollment_date": "3/23/2020",
    "gpa": "1.87",
    "external_system": "internal"
  },
  {
    "student_id": "344",
    "first_name": "Octavius",
    "last_name": "Paff",
    "age": "25",
    "email": "opaff9j@usgs.gov",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "12/21/2020",
    "gpa": "0.36",
    "external_system": "internal"
  },
  {
    "student_id": "352",
    "first_name": "Geri",
    "last_name": "Vial",
    "age": "19",
    "email": "gvial9r@paginegialle.it",
    "country": "United States",
    "postal_code": "80920",
    "favorite_color": "blue",
    "enrollment_date": "4/4/2022",
    "gpa": "3.32",
    "external_system": "internal"
  },
  {
    "student_id": "353",
    "first_name": "Scarlet",
    "last_name": "Canon",
    "age": "22",
    "email": "scanon9s@quantcast.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "4/3/2022",
    "gpa": "1.09",
    "external_system": "internal"
  },
  {
    "student_id": "354",
    "first_name": "Elayne",
    "last_name": "Daniel",
    "age": "25",
    "email": "edaniel9t@npr.org",
    "country": "Brazil",
    "postal_code": "88330-000",
    "favorite_color": "green",
    "enrollment_date": "12/24/2022",
    "gpa": "2.27",
    "external_system": "internal"
  },
  {
    "student_id": "355",
    "first_name": "Nicolais",
    "last_name": "Jalland",
    "age": "25",
    "email": "njalland9u@canalblog.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "6/5/2020",
    "gpa": "3.63",
    "external_system": "internal"
  },
  {
    "student_id": "362",
    "first_name": "Gertrude",
    "last_name": "Lydford",
    "age": "24",
    "email": "glydforda1@edublogs.org",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "3/21/2022",
    "gpa": "2.16",
    "external_system": "internal"
  },
  {
    "student_id": "370",
    "first_name": "Darnall",
    "last_name": "Jackson",
    "age": "23",
    "email": "djacksona9@accuweather.com",
    "country": "Portugal",
    "postal_code": "3525-606",
    "favorite_color": "blue",
    "enrollment_date": "8/17/2021",
    "gpa": "3.57",
    "external_system": "internal"
  },
  {
    "student_id": "378",
    "first_name": "Greta",
    "last_name": "Jewson",
    "age": "20",
    "email": "gjewsonah@1und1.de",
    "country": "Brazil",
    "postal_code": "53600-000",
    "favorite_color": "blue",
    "enrollment_date": "2/19/2020",
    "gpa": "2.64",
    "external_system": "internal"
  },
  {
    "student_id": "394",
    "first_name": "Lucina",
    "last_name": "Grangier",
    "age": "18",
    "email": "lgrangierax@harvard.edu",
    "country": "Brazil",
    "postal_code": "55590-000",
    "favorite_color": "green",
    "enrollment_date": "6/30/2022",
    "gpa": "3.77",
    "external_system": "internal"
  },
  {
    "student_id": "397",
    "first_name": "Chrystel",
    "last_name": "Kupker",
    "age": "23",
    "email": "ckupkerb0@cocolog-nifty.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "10/15/2021",
    "gpa": "2.57",
    "external_system": "internal"
  },
  {
    "student_id": "400",
    "first_name": "Benji",
    "last_name": "Ertel",
    "age": "23",
    "email": "bertelb3@yellowpages.com",
    "country": "Mauritius",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/13/2022",
    "gpa": "2.24",
    "external_system": "internal"
  },
  {
    "student_id": "406",
    "first_name": "Beatriz",
    "last_name": "Kaiser",
    "age": "24",
    "email": "bkaiserb9@qq.com",
    "country": "Malaysia",
    "postal_code": "50720",
    "favorite_color": "blue",
    "enrollment_date": "8/6/2022",
    "gpa": "2.36",
    "external_system": "internal"
  },
  {
    "student_id": "407",
    "first_name": "Madelyn",
    "last_name": "Blackster",
    "age": "22",
    "email": "mblacksterba@ucoz.com",
    "country": "Brazil",
    "postal_code": "78390-000",
    "favorite_color": "green",
    "enrollment_date": "2/2/2021",
    "gpa": "2.6",
    "external_system": "internal"
  },
  {
    "student_id": "416",
    "first_name": "Norman",
    "last_name": "Doughton",
    "age": "21",
    "email": "ndoughtonbj@utexas.edu",
    "country": "Poland",
    "postal_code": "72-203",
    "favorite_color": "green",
    "enrollment_date": "9/7/2022",
    "gpa": "2.02",
    "external_system": "internal"
  },
  {
    "student_id": "417",
    "first_name": "Cairistiona",
    "last_name": "Hulmes",
    "age": "19",
    "email": "chulmesbk@cisco.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "10/5/2022",
    "gpa": "0.74",
    "external_system": "internal"
  },
  {
    "student_id": "419",
    "first_name": "Emmie",
    "last_name": "Cody",
    "age": "24",
    "email": "ecodybm@mysql.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "3/28/2022",
    "gpa": "1.4",
    "external_system": "internal"
  },
  {
    "student_id": "434",
    "first_name": "Dimitri",
    "last_name": "O Mullen",
    "age": "23",
    "email": "domullenc1@fastcompany.com",
    "country": "Czech Republic",
    "postal_code": "411 45",
    "favorite_color": "blue",
    "enrollment_date": "2/9/2020",
    "gpa": "0.8",
    "external_system": "internal"
  },
  {
    "student_id": "444",
    "first_name": "Cindee",
    "last_name": "Slimon",
    "age": "19",
    "email": "cslimoncb@illinois.edu",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "12/3/2020",
    "gpa": "2.14",
    "external_system": "internal"
  },
  {
    "student_id": "446",
    "first_name": "Linzy",
    "last_name": "Domokos",
    "age": "22",
    "email": "ldomokoscd@plala.or.jp",
    "country": "Portugal",
    "postal_code": "4880-235",
    "favorite_color": "red",
    "enrollment_date": "1/12/2021",
    "gpa": "3.47",
    "external_system": "internal"
  },
  {
    "student_id": "447",
    "first_name": "Claudio",
    "last_name": "Le Breton",
    "age": "18",
    "email": "clebretonce@fema.gov",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "3/7/2021",
    "gpa": "3.7",
    "external_system": "internal"
  },
  {
    "student_id": "459",
    "first_name": "Wyatan",
    "last_name": "Coulson",
    "age": "21",
    "email": "wcoulsoncq@oaic.gov.au",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/25/2021",
    "gpa": "1.41",
    "external_system": "internal"
  },
  {
    "student_id": "462",
    "first_name": "Crystal",
    "last_name": "Stollhofer",
    "age": "22",
    "email": "cstollhoferct@wikimedia.org",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/9/2021",
    "gpa": "3.45",
    "external_system": "internal"
  },
  {
    "student_id": "467",
    "first_name": "Cathy",
    "last_name": "Stentiford",
    "age": "23",
    "email": "cstentifordcy@ebay.co.uk",
    "country": "Portugal",
    "postal_code": "5320-305",
    "favorite_color": "blue",
    "enrollment_date": "9/17/2021",
    "gpa": "1.51",
    "external_system": "internal"
  },
  {
    "student_id": "470",
    "first_name": "Neila",
    "last_name": "Barthrup",
    "age": "23",
    "email": "nbarthrupd1@jimdo.com",
    "country": "United States",
    "postal_code": "47747",
    "favorite_color": "red",
    "enrollment_date": "12/4/2022",
    "gpa": "0.2",
    "external_system": "internal"
  },
  {
    "student_id": "472",
    "first_name": "Baron",
    "last_name": "Slowan",
    "age": "24",
    "email": "bslowand3@pbs.org",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/20/2020",
    "gpa": "0.85",
    "external_system": "internal"
  },
  {
    "student_id": "473",
    "first_name": "Emilia",
    "last_name": "Viggers",
    "age": "18",
    "email": "eviggersd4@friendfeed.com",
    "country": "Poland",
    "postal_code": "83-034",
    "favorite_color": "green",
    "enrollment_date": "10/25/2021",
    "gpa": "2.47",
    "external_system": "internal"
  },
  {
    "student_id": "475",
    "first_name": "Anstice",
    "last_name": "Fayter",
    "age": "20",
    "email": "afayterd6@ted.com",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/28/2021",
    "gpa": "0.25",
    "external_system": "internal"
  },
  {
    "student_id": "479",
    "first_name": "Melisent",
    "last_name": "Lepper",
    "age": "21",
    "email": "mlepperda@newsvine.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "12/5/2021",
    "gpa": "2.52",
    "external_system": "internal"
  },
  {
    "student_id": "481",
    "first_name": "Shermie",
    "last_name": "Roseblade",
    "age": "23",
    "email": "srosebladedc@bbb.org",
    "country": "Russia",
    "postal_code": "152850",
    "favorite_color": "red",
    "enrollment_date": "10/16/2020",
    "gpa": "0.55",
    "external_system": "internal"
  },
  {
    "student_id": "500",
    "first_name": "Faith",
    "last_name": "Vale",
    "age": "24",
    "email": "fvaledv@friendfeed.com",
    "country": "Syria",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/21/2022",
    "gpa": "0.15",
    "external_system": "internal"
  },
  {
    "student_id": "503",
    "first_name": "Sheelah",
    "last_name": "Finnemore",
    "age": "22",
    "email": "sfinnemoredy@so-net.ne.jp",
    "country": "Albania",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "9/23/2022",
    "gpa": "3.68",
    "external_system": "internal"
  },
  {
    "student_id": "520",
    "first_name": "Mirabelle",
    "last_name": "Pala",
    "age": "25",
    "email": "mpalaef@google.it",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "2/25/2020",
    "gpa": "2.31",
    "external_system": "internal"
  },
  {
    "student_id": "521",
    "first_name": "Dusty",
    "last_name": "Shearston",
    "age": "20",
    "email": "dshearstoneg@marketwatch.com",
    "country": "Philippines",
    "postal_code": "1063",
    "favorite_color": "red",
    "enrollment_date": "6/17/2020",
    "gpa": "3.52",
    "external_system": "internal"
  },
  {
    "student_id": "525",
    "first_name": "Rois",
    "last_name": "Tallyn",
    "age": "22",
    "email": "rtallynek@marketwatch.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/26/2022",
    "gpa": "2.14",
    "external_system": "internal"
  },
  {
    "student_id": "530",
    "first_name": "Alla",
    "last_name": "Soane",
    "age": "21",
    "email": "asoaneep@foxnews.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "9/29/2021",
    "gpa": "2.07",
    "external_system": "internal"
  },
  {
    "student_id": "539",
    "first_name": "Lemuel",
    "last_name": "Momery",
    "age": "18",
    "email": "lmomeryey@edublogs.org",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "11/5/2021",
    "gpa": "2.67",
    "external_system": "internal"
  },
  {
    "student_id": "541",
    "first_name": "Barron",
    "last_name": "Johnke",
    "age": "23",
    "email": "bjohnkef0@opensource.org",
    "country": "Saint Helena",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "6/26/2021",
    "gpa": "2.06",
    "external_system": "internal"
  },
  {
    "student_id": "542",
    "first_name": "Kacie",
    "last_name": "Reichert",
    "age": "18",
    "email": "kreichertf1@squidoo.com",
    "country": "Malaysia",
    "postal_code": "50943",
    "favorite_color": "green",
    "enrollment_date": "5/14/2021",
    "gpa": "3.8",
    "external_system": "internal"
  },
  {
    "student_id": "543",
    "first_name": "Amalea",
    "last_name": "Gillbanks",
    "age": "18",
    "email": "agillbanksf2@scientificamerican.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "4/17/2021",
    "gpa": "2.58",
    "external_system": "internal"
  },
  {
    "student_id": "544",
    "first_name": "Thatcher",
    "last_name": "Musk",
    "age": "18",
    "email": "tmuskf3@imgur.com",
    "country": "Poland",
    "postal_code": "43-340",
    "favorite_color": "green",
    "enrollment_date": "10/4/2022",
    "gpa": "1.17",
    "external_system": "internal"
  },
  {
    "student_id": "545",
    "first_name": "Yorker",
    "last_name": "Swarbrick",
    "age": "19",
    "email": "yswarbrickf4@chicagotribune.com",
    "country": "Russia",
    "postal_code": "422826",
    "favorite_color": "red",
    "enrollment_date": "4/17/2020",
    "gpa": "1.4",
    "external_system": "internal"
  },
  {
    "student_id": "550",
    "first_name": "Kiri",
    "last_name": "Combes",
    "age": "25",
    "email": "kcombesf9@ask.com",
    "country": "France",
    "postal_code": "06254 CEDEX",
    "favorite_color": "blue",
    "enrollment_date": "4/26/2021",
    "gpa": "1.59",
    "external_system": "internal"
  },
  {
    "student_id": "553",
    "first_name": "Adi",
    "last_name": "Cadden",
    "age": "20",
    "email": "acaddenfc@sohu.com",
    "country": "Poland",
    "postal_code": "43-188",
    "favorite_color": "blue",
    "enrollment_date": "8/30/2021",
    "gpa": "2.16",
    "external_system": "internal"
  },
  {
    "student_id": "557",
    "first_name": "Shepherd",
    "last_name": "Spyby",
    "age": "19",
    "email": "sspybyfg@vk.com",
    "country": "Cyprus",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "1/21/2020",
    "gpa": "0.51",
    "external_system": "internal"
  },
  {
    "student_id": "561",
    "first_name": "Boy",
    "last_name": "Clendinning",
    "age": "18",
    "email": "bclendinningfk@wikia.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "11/24/2022",
    "gpa": "1.18",
    "external_system": "internal"
  },
  {
    "student_id": "563",
    "first_name": "Lucila",
    "last_name": "Maffia",
    "age": "23",
    "email": "lmaffiafm@google.fr",
    "country": "Philippines",
    "postal_code": "4328",
    "favorite_color": "green",
    "enrollment_date": "6/13/2022",
    "gpa": "2.79",
    "external_system": "internal"
  },
  {
    "student_id": "572",
    "first_name": "Emily",
    "last_name": "Kuhnke",
    "age": "23",
    "email": "ekuhnkefv@networkadvertising.org",
    "country": "Mexico",
    "postal_code": "32127",
    "favorite_color": "green",
    "enrollment_date": "5/12/2020",
    "gpa": "2.13",
    "external_system": "internal"
  },
  {
    "student_id": "573",
    "first_name": "Dolley",
    "last_name": "Roblou",
    "age": "25",
    "email": "drobloufw@fda.gov",
    "country": "Philippines",
    "postal_code": "2007",
    "favorite_color": "blue",
    "enrollment_date": "1/25/2020",
    "gpa": "3.48",
    "external_system": "internal"
  },
  {
    "student_id": "576",
    "first_name": "Cherida",
    "last_name": "Trusler",
    "age": "25",
    "email": "ctruslerfz@reddit.com",
    "country": "Brazil",
    "postal_code": "18560-000",
    "favorite_color": "blue",
    "enrollment_date": "10/5/2020",
    "gpa": "0.01",
    "external_system": "internal"
  },
  {
    "student_id": "579",
    "first_name": "Tallou",
    "last_name": "Spaxman",
    "age": "24",
    "email": "tspaxmang2@indiegogo.com",
    "country": "South Korea",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "12/15/2020",
    "gpa": "2.41",
    "external_system": "internal"
  },
  {
    "student_id": "582",
    "first_name": "Sascha",
    "last_name": "Northgraves",
    "age": "24",
    "email": "snorthgravesg5@godaddy.com",
    "country": "Uruguay",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/21/2020",
    "gpa": "0.64",
    "external_system": "internal"
  },
  {
    "student_id": "584",
    "first_name": "Dorie",
    "last_name": "Schoroder",
    "age": "23",
    "email": "dschoroderg7@ibm.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "7/23/2020",
    "gpa": "0.96",
    "external_system": "internal"
  },
  {
    "student_id": "591",
    "first_name": "Jean",
    "last_name": "Murra",
    "age": "22",
    "email": "jmurrage@examiner.com",
    "country": "Canada",
    "postal_code": "L2T",
    "favorite_color": "blue",
    "enrollment_date": "1/31/2022",
    "gpa": "0.55",
    "external_system": "internal"
  },
  {
    "student_id": "592",
    "first_name": "Babb",
    "last_name": "Mayo",
    "age": "22",
    "email": "bmayogf@ucoz.ru",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "12/25/2022",
    "gpa": "0.54",
    "external_system": "internal"
  },
  {
    "student_id": "598",
    "first_name": "Kellen",
    "last_name": "Wickardt",
    "age": "20",
    "email": "kwickardtgl@i2i.jp",
    "country": "France",
    "postal_code": "76418 CEDEX 9",
    "favorite_color": "blue",
    "enrollment_date": "2/15/2021",
    "gpa": "1.24",
    "external_system": "internal"
  },
  {
    "student_id": "606",
    "first_name": "Bertrando",
    "last_name": "Costock",
    "age": "21",
    "email": "bcostockgt@vk.com",
    "country": "Armenia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "9/9/2022",
    "gpa": "3.34",
    "external_system": "internal"
  },
  {
    "student_id": "607",
    "first_name": "Erma",
    "last_name": "Mizzi",
    "age": "25",
    "email": "emizzigu@hc360.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "12/16/2020",
    "gpa": "0.45",
    "external_system": "internal"
  },
  {
    "student_id": "618",
    "first_name": "Garwin",
    "last_name": "Bain",
    "age": "18",
    "email": "gbainh5@seattletimes.com",
    "country": "Iran",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/8/2020",
    "gpa": "3.37",
    "external_system": "internal"
  },
  {
    "student_id": "620",
    "first_name": "Fannie",
    "last_name": "Messham",
    "age": "23",
    "email": "fmesshamh7@globo.com",
    "country": "Nepal",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "2/8/2021",
    "gpa": "3.1",
    "external_system": "internal"
  },
  {
    "student_id": "623",
    "first_name": "Cello",
    "last_name": "Bartlomiej",
    "age": "20",
    "email": "cbartlomiejha@businesswire.com",
    "country": "Lithuania",
    "postal_code": "64037",
    "favorite_color": "red",
    "enrollment_date": "6/13/2021",
    "gpa": "1.28",
    "external_system": "internal"
  },
  {
    "student_id": "628",
    "first_name": "Frannie",
    "last_name": "Fredy",
    "age": "25",
    "email": "ffredyhf@npr.org",
    "country": "Poland",
    "postal_code": "84-107",
    "favorite_color": "red",
    "enrollment_date": "8/27/2021",
    "gpa": "0.67",
    "external_system": "internal"
  },
  {
    "student_id": "630",
    "first_name": "Gwenette",
    "last_name": "Few",
    "age": "25",
    "email": "gfewhh@blog.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/30/2022",
    "gpa": "2.49",
    "external_system": "internal"
  },
  {
    "student_id": "631",
    "first_name": "Ambrosi",
    "last_name": "Cottle",
    "age": "20",
    "email": "acottlehi@imageshack.us",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "4/13/2021",
    "gpa": "3.52",
    "external_system": "internal"
  },
  {
    "student_id": "633",
    "first_name": "Web",
    "last_name": "Pook",
    "age": "23",
    "email": "wpookhk@1und1.de",
    "country": "Brazil",
    "postal_code": "15440-000",
    "favorite_color": "blue",
    "enrollment_date": "10/12/2021",
    "gpa": "3.12",
    "external_system": "internal"
  },
  {
    "student_id": "648",
    "first_name": "Fernanda",
    "last_name": "Casero",
    "age": "18",
    "email": "fcaserohz@amazon.co.uk",
    "country": "Zimbabwe",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/3/2022",
    "gpa": "1.08",
    "external_system": "internal"
  },
  {
    "student_id": "649",
    "first_name": "Minor",
    "last_name": "Jendrassik",
    "age": "21",
    "email": "mjendrassiki0@oracle.com",
    "country": "Iran",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/28/2020",
    "gpa": "1.26",
    "external_system": "internal"
  },
  {
    "student_id": "656",
    "first_name": "Matilde",
    "last_name": "Barracks",
    "age": "25",
    "email": "mbarracksi7@sphinn.com",
    "country": "Sweden",
    "postal_code": "850 09",
    "favorite_color": "green",
    "enrollment_date": "12/28/2021",
    "gpa": "0.54",
    "external_system": "internal"
  },
  {
    "student_id": "659",
    "first_name": "Liana",
    "last_name": "West-Frimley",
    "age": "23",
    "email": "lwestfrimleyia@github.io",
    "country": "Colombia",
    "postal_code": "250038",
    "favorite_color": "green",
    "enrollment_date": "2/19/2021",
    "gpa": "0.24",
    "external_system": "internal"
  },
  {
    "student_id": "667",
    "first_name": "Martynne",
    "last_name": "Jahnel",
    "age": "24",
    "email": "mjahnelii@cpanel.net",
    "country": "Portugal",
    "postal_code": "4585-586",
    "favorite_color": "blue",
    "enrollment_date": "5/9/2022",
    "gpa": "1.79",
    "external_system": "internal"
  },
  {
    "student_id": "676",
    "first_name": "Johna",
    "last_name": "Crosston",
    "age": "18",
    "email": "jcrosstonir@paypal.com",
    "country": "Philippines",
    "postal_code": "5507",
    "favorite_color": "green",
    "enrollment_date": "5/10/2022",
    "gpa": "0.3",
    "external_system": "internal"
  },
  {
    "student_id": "678",
    "first_name": "Kaitlynn",
    "last_name": "Casterton",
    "age": "24",
    "email": "kcastertonit@com.com",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/8/2021",
    "gpa": "2.84",
    "external_system": "internal"
  },
  {
    "student_id": "680",
    "first_name": "Justis",
    "last_name": "Euplate",
    "age": "21",
    "email": "jeuplateiv@slate.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "1/5/2020",
    "gpa": "0.49",
    "external_system": "internal"
  },
  {
    "student_id": "685",
    "first_name": "Loy",
    "last_name": "Bergin",
    "age": "25",
    "email": "lberginj0@soup.io",
    "country": "Canada",
    "postal_code": "P7L",
    "favorite_color": "red",
    "enrollment_date": "3/20/2020",
    "gpa": "2.71",
    "external_system": "internal"
  },
  {
    "student_id": "687",
    "first_name": "Ericka",
    "last_name": "Muttock",
    "age": "23",
    "email": "emuttockj2@reverbnation.com",
    "country": "Guyana",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "3/4/2021",
    "gpa": "0.69",
    "external_system": "internal"
  },
  {
    "student_id": "688",
    "first_name": "Sigvard",
    "last_name": "Pomeroy",
    "age": "25",
    "email": "spomeroyj3@istockphoto.com",
    "country": "Colombia",
    "postal_code": "150477",
    "favorite_color": "green",
    "enrollment_date": "3/5/2022",
    "gpa": "3.71",
    "external_system": "internal"
  },
  {
    "student_id": "689",
    "first_name": "Costa",
    "last_name": "Kohring",
    "age": "25",
    "email": "ckohringj4@un.org",
    "country": "Brazil",
    "postal_code": "58550-000",
    "favorite_color": "red",
    "enrollment_date": "6/21/2021",
    "gpa": "2.88",
    "external_system": "internal"
  },
  {
    "student_id": "695",
    "first_name": "Gherardo",
    "last_name": "Dmych",
    "age": "18",
    "email": "gdmychja@multiply.com",
    "country": "Philippines",
    "postal_code": "4502",
    "favorite_color": "green",
    "enrollment_date": "1/27/2020",
    "gpa": "2.53",
    "external_system": "internal"
  },
  {
    "student_id": "696",
    "first_name": "Giusto",
    "last_name": "Maven",
    "age": "21",
    "email": "gmavenjb@gravatar.com",
    "country": "Ecuador",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "12/7/2021",
    "gpa": "0.68",
    "external_system": "internal"
  },
  {
    "student_id": "703",
    "first_name": "Odo",
    "last_name": "Snelle",
    "age": "24",
    "email": "osnelleji@squidoo.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "1/24/2022",
    "gpa": "0.96",
    "external_system": "internal"
  },
  {
    "student_id": "707",
    "first_name": "Jamie",
    "last_name": "Pummell",
    "age": "23",
    "email": "jpummelljm@walmart.com",
    "country": "Peru",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/2/2021",
    "gpa": "0.81",
    "external_system": "internal"
  },
  {
    "student_id": "712",
    "first_name": "Witty",
    "last_name": "Mackett",
    "age": "21",
    "email": "wmackettjr@csmonitor.com",
    "country": "United States",
    "postal_code": "71115",
    "favorite_color": "green",
    "enrollment_date": "7/24/2021",
    "gpa": "1.01",
    "external_system": "internal"
  },
  {
    "student_id": "714",
    "first_name": "Toiboid",
    "last_name": "Witsey",
    "age": "23",
    "email": "twitseyjt@privacy.gov.au",
    "country": "France",
    "postal_code": "93604 CEDEX",
    "favorite_color": "red",
    "enrollment_date": "9/24/2022",
    "gpa": "3.54",
    "external_system": "internal"
  },
  {
    "student_id": "715",
    "first_name": "Karon",
    "last_name": "Cahillane",
    "age": "21",
    "email": "kcahillaneju@springer.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/17/2022",
    "gpa": "1.44",
    "external_system": "internal"
  },
  {
    "student_id": "716",
    "first_name": "Layne",
    "last_name": "Shepherdson",
    "age": "23",
    "email": "lshepherdsonjv@yale.edu",
    "country": "Mexico",
    "postal_code": "93608",
    "favorite_color": "green",
    "enrollment_date": "7/20/2022",
    "gpa": "1.12",
    "external_system": "internal"
  },
  {
    "student_id": "724",
    "first_name": "Suellen",
    "last_name": "Blake",
    "age": "25",
    "email": "sblakek3@reddit.com",
    "country": "Syria",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/10/2021",
    "gpa": "1.23",
    "external_system": "internal"
  },
  {
    "student_id": "729",
    "first_name": "Hamilton",
    "last_name": "Whitman",
    "age": "24",
    "email": "hwhitmank8@histats.com",
    "country": "Japan",
    "postal_code": "987-0172",
    "favorite_color": "blue",
    "enrollment_date": "7/3/2020",
    "gpa": "2.0",
    "external_system": "internal"
  },
  {
    "student_id": "738",
    "first_name": "Costa",
    "last_name": "Leaver",
    "age": "25",
    "email": "cleaverkh@slate.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/14/2020",
    "gpa": "0.34",
    "external_system": "internal"
  },
  {
    "student_id": "740",
    "first_name": "Dorthy",
    "last_name": "Ridgway",
    "age": "22",
    "email": "dridgwaykj@ow.ly",
    "country": "Russia",
    "postal_code": "188360",
    "favorite_color": "blue",
    "enrollment_date": "4/29/2020",
    "gpa": "0.85",
    "external_system": "internal"
  },
  {
    "student_id": "745",
    "first_name": "Sissy",
    "last_name": "Landa",
    "age": "21",
    "email": "slandako@msn.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/5/2020",
    "gpa": "1.86",
    "external_system": "internal"
  },
  {
    "student_id": "749",
    "first_name": "Gianina",
    "last_name": "Huetson",
    "age": "20",
    "email": "ghuetsonks@moonfruit.com",
    "country": "Republic of the Congo",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "12/7/2022",
    "gpa": "0.4",
    "external_system": "internal"
  },
  {
    "student_id": "753",
    "first_name": "Bronnie",
    "last_name": "Ronchetti",
    "age": "23",
    "email": "bronchettikw@ft.com",
    "country": "Ethiopia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "4/22/2021",
    "gpa": "1.93",
    "external_system": "internal"
  },
  {
    "student_id": "757",
    "first_name": "Ingram",
    "last_name": "Tilt",
    "age": "18",
    "email": "itiltl0@shareasale.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/24/2021",
    "gpa": "3.46",
    "external_system": "internal"
  },
  {
    "student_id": "758",
    "first_name": "Hendrik",
    "last_name": "Greatbanks",
    "age": "18",
    "email": "hgreatbanksl1@ihg.com",
    "country": "France",
    "postal_code": "18035 CEDEX",
    "favorite_color": "blue",
    "enrollment_date": "3/10/2022",
    "gpa": "3.03",
    "external_system": "internal"
  },
  {
    "student_id": "759",
    "first_name": "Foster",
    "last_name": "Jiggins",
    "age": "24",
    "email": "fjigginsl2@ibm.com",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/27/2022",
    "gpa": "2.78",
    "external_system": "internal"
  },
  {
    "student_id": "765",
    "first_name": "Chicky",
    "last_name": "Kinny",
    "age": "22",
    "email": "ckinnyl8@yale.edu",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "1/17/2020",
    "gpa": "0.32",
    "external_system": "internal"
  },
  {
    "student_id": "768",
    "first_name": "Gustavus",
    "last_name": "Harper",
    "age": "18",
    "email": "gharperlb@last.fm",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "8/8/2020",
    "gpa": "0.6",
    "external_system": "internal"
  },
  {
    "student_id": "773",
    "first_name": "Cristi",
    "last_name": "Annes",
    "age": "18",
    "email": "canneslg@gnu.org",
    "country": "Japan",
    "postal_code": "929-0417",
    "favorite_color": "red",
    "enrollment_date": "6/15/2022",
    "gpa": "0.92",
    "external_system": "internal"
  },
  {
    "student_id": "774",
    "first_name": "Mickey",
    "last_name": "Bartoloma",
    "age": "20",
    "email": "mbartolomalh@moonfruit.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/2/2020",
    "gpa": "4.0",
    "external_system": "internal"
  },
  {
    "student_id": "781",
    "first_name": "Boigie",
    "last_name": "Batters",
    "age": "23",
    "email": "bbatterslo@irs.gov",
    "country": "Tanzania",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/12/2022",
    "gpa": "1.8",
    "external_system": "internal"
  },
  {
    "student_id": "788",
    "first_name": "Malachi",
    "last_name": "Curds",
    "age": "18",
    "email": "mcurdslv@slideshare.net",
    "country": "Thailand",
    "postal_code": "75110",
    "favorite_color": "red",
    "enrollment_date": "12/7/2020",
    "gpa": "3.81",
    "external_system": "internal"
  },
  {
    "student_id": "793",
    "first_name": "Giffard",
    "last_name": "Warcop",
    "age": "22",
    "email": "gwarcopm0@cnn.com",
    "country": "France",
    "postal_code": "49804 CEDEX",
    "favorite_color": "green",
    "enrollment_date": "2/14/2021",
    "gpa": "1.07",
    "external_system": "internal"
  },
  {
    "student_id": "798",
    "first_name": "Lorne",
    "last_name": "Edsall",
    "age": "25",
    "email": "ledsallm5@google.com.hk",
    "country": "Russia",
    "postal_code": "607224",
    "favorite_color": "green",
    "enrollment_date": "12/29/2022",
    "gpa": "0.87",
    "external_system": "internal"
  },
  {
    "student_id": "803",
    "first_name": "Paulie",
    "last_name": "Conningham",
    "age": "25",
    "email": "pconninghamma@google.com.hk",
    "country": "Peru",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "8/12/2020",
    "gpa": "0.62",
    "external_system": "internal"
  },
  {
    "student_id": "804",
    "first_name": "Milka",
    "last_name": "Rhymes",
    "age": "21",
    "email": "mrhymesmb@stumbleupon.com",
    "country": "Colombia",
    "postal_code": "545518",
    "favorite_color": "blue",
    "enrollment_date": "12/30/2022",
    "gpa": "1.53",
    "external_system": "internal"
  },
  {
    "student_id": "806",
    "first_name": "Anna-diana",
    "last_name": "Awde",
    "age": "20",
    "email": "aawdemd@java.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/6/2022",
    "gpa": "1.53",
    "external_system": "internal"
  },
  {
    "student_id": "808",
    "first_name": "Rica",
    "last_name": "Fransemai",
    "age": "22",
    "email": "rfransemaimf@desdev.cn",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/14/2020",
    "gpa": "2.09",
    "external_system": "internal"
  },
  {
    "student_id": "809",
    "first_name": "Storm",
    "last_name": "Rudgard",
    "age": "21",
    "email": "srudgardmg@cam.ac.uk",
    "country": "France",
    "postal_code": "75321 CEDEX 07",
    "favorite_color": "red",
    "enrollment_date": "12/12/2021",
    "gpa": "1.33",
    "external_system": "internal"
  },
  {
    "student_id": "813",
    "first_name": "Cindee",
    "last_name": "McLucky",
    "age": "19",
    "email": "cmcluckymk@arstechnica.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "10/14/2022",
    "gpa": "3.59",
    "external_system": "internal"
  },
  {
    "student_id": "817",
    "first_name": "Lenora",
    "last_name": "Realph",
    "age": "21",
    "email": "lrealphmo@privacy.gov.au",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "3/18/2021",
    "gpa": "1.49",
    "external_system": "internal"
  },
  {
    "student_id": "819",
    "first_name": "Conant",
    "last_name": "Geggus",
    "age": "20",
    "email": "cgeggusmq@theglobeandmail.com",
    "country": "Russia",
    "postal_code": "461149",
    "favorite_color": "green",
    "enrollment_date": "10/31/2021",
    "gpa": "2.47",
    "external_system": "internal"
  },
  {
    "student_id": "822",
    "first_name": "Marianne",
    "last_name": "Tomkys",
    "age": "23",
    "email": "mtomkysmt@webnode.com",
    "country": "Nigeria",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "9/18/2022",
    "gpa": "1.66",
    "external_system": "internal"
  },
  {
    "student_id": "825",
    "first_name": "Gerianne",
    "last_name": "Nenci",
    "age": "24",
    "email": "gnencimw@msu.edu",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "2/5/2020",
    "gpa": "0.09",
    "external_system": "internal"
  },
  {
    "student_id": "829",
    "first_name": "Caesar",
    "last_name": "Thyng",
    "age": "25",
    "email": "cthyngn0@yahoo.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/30/2020",
    "gpa": "1.51",
    "external_system": "internal"
  },
  {
    "student_id": "831",
    "first_name": "Loydie",
    "last_name": "Malenoir",
    "age": "21",
    "email": "lmalenoirn2@omniture.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "5/23/2020",
    "gpa": "0.73",
    "external_system": "internal"
  },
  {
    "student_id": "833",
    "first_name": "Cecily",
    "last_name": "Blaydes",
    "age": "21",
    "email": "cblaydesn4@biglobe.ne.jp",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/19/2020",
    "gpa": "3.53",
    "external_system": "internal"
  },
  {
    "student_id": "835",
    "first_name": "Corbet",
    "last_name": "Bettley",
    "age": "24",
    "email": "cbettleyn6@vimeo.com",
    "country": "United States",
    "postal_code": "85284",
    "favorite_color": "red",
    "enrollment_date": "2/26/2021",
    "gpa": "0.32",
    "external_system": "internal"
  },
  {
    "student_id": "844",
    "first_name": "Tiffie",
    "last_name": "Druitt",
    "age": "20",
    "email": "tdruittnf@shareasale.com",
    "country": "Canada",
    "postal_code": "G3M",
    "favorite_color": "blue",
    "enrollment_date": "6/1/2022",
    "gpa": "3.89",
    "external_system": "internal"
  },
  {
    "student_id": "845",
    "first_name": "Nata",
    "last_name": "Baumer",
    "age": "22",
    "email": "nbaumerng@epa.gov",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "9/5/2022",
    "gpa": "3.24",
    "external_system": "internal"
  },
  {
    "student_id": "846",
    "first_name": "Kirstyn",
    "last_name": "Lees",
    "age": "25",
    "email": "kleesnh@guardian.co.uk",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "3/26/2022",
    "gpa": "1.77",
    "external_system": "internal"
  },
  {
    "student_id": "847",
    "first_name": "Melonie",
    "last_name": "Carlesso",
    "age": "19",
    "email": "mcarlessoni@usgs.gov",
    "country": "Serbia",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "4/17/2021",
    "gpa": "1.74",
    "external_system": "internal"
  },
  {
    "student_id": "854",
    "first_name": "Brose",
    "last_name": "MacAree",
    "age": "22",
    "email": "bmacareenp@w3.org",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "10/22/2022",
    "gpa": "0.23",
    "external_system": "internal"
  },
  {
    "student_id": "856",
    "first_name": "Rodolph",
    "last_name": "Bowes",
    "age": "24",
    "email": "rbowesnr@mozilla.org",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/7/2020",
    "gpa": "3.7",
    "external_system": "internal"
  },
  {
    "student_id": "865",
    "first_name": "Agretha",
    "last_name": "Ely",
    "age": "25",
    "email": "aelyo0@typepad.com",
    "country": "Russia",
    "postal_code": "171658",
    "favorite_color": "blue",
    "enrollment_date": "3/3/2020",
    "gpa": "2.1",
    "external_system": "internal"
  },
  {
    "student_id": "868",
    "first_name": "Zachariah",
    "last_name": "Albert",
    "age": "23",
    "email": "zalberto3@netvibes.com",
    "country": "Afghanistan",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "7/8/2022",
    "gpa": "1.15",
    "external_system": "internal"
  },
  {
    "student_id": "870",
    "first_name": "Moina",
    "last_name": "Formoy",
    "age": "21",
    "email": "mformoyo5@paypal.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "5/12/2022",
    "gpa": "0.42",
    "external_system": "internal"
  },
  {
    "student_id": "873",
    "first_name": "Dollie",
    "last_name": "Letchford",
    "age": "18",
    "email": "dletchfordo8@feedburner.com",
    "country": "France",
    "postal_code": "95011 CEDEX",
    "favorite_color": "blue",
    "enrollment_date": "10/4/2021",
    "gpa": "2.43",
    "external_system": "internal"
  },
  {
    "student_id": "874",
    "first_name": "Corabella",
    "last_name": "Jeffree",
    "age": "22",
    "email": "cjeffreeo9@youku.com",
    "country": "Poland",
    "postal_code": "82-505",
    "favorite_color": "green",
    "enrollment_date": "9/7/2020",
    "gpa": "1.51",
    "external_system": "internal"
  },
  {
    "student_id": "879",
    "first_name": "Shanta",
    "last_name": "Ettels",
    "age": "23",
    "email": "settelsoe@sciencedirect.com",
    "country": "Turkey",
    "postal_code": "34829",
    "favorite_color": "red",
    "enrollment_date": "10/26/2021",
    "gpa": "0.14",
    "external_system": "internal"
  },
  {
    "student_id": "881",
    "first_name": "Louisa",
    "last_name": "Rait",
    "age": "22",
    "email": "lraitog@amazon.co.jp",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/19/2021",
    "gpa": "0.34",
    "external_system": "internal"
  },
  {
    "student_id": "885",
    "first_name": "Paxton",
    "last_name": "Mosdill",
    "age": "20",
    "email": "pmosdillok@shutterfly.com",
    "country": "Russia",
    "postal_code": "309311",
    "favorite_color": "green",
    "enrollment_date": "10/7/2022",
    "gpa": "1.89",
    "external_system": "internal"
  },
  {
    "student_id": "889",
    "first_name": "Sheena",
    "last_name": "Spaice",
    "age": "18",
    "email": "sspaiceoo@etsy.com",
    "country": "Palestinian Territory",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "12/27/2022",
    "gpa": "3.51",
    "external_system": "internal"
  },
  {
    "student_id": "898",
    "first_name": "Odo",
    "last_name": "Tooker",
    "age": "24",
    "email": "otookerox@state.gov",
    "country": "Kyrgyzstan",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/7/2021",
    "gpa": "3.98",
    "external_system": "internal"
  },
  {
    "student_id": "907",
    "first_name": "Flo",
    "last_name": "Pershouse",
    "age": "18",
    "email": "fpershousep6@cbsnews.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/19/2021",
    "gpa": "0.57",
    "external_system": "internal"
  },
  {
    "student_id": "910",
    "first_name": "Rhody",
    "last_name": "Howard - Gater",
    "age": "23",
    "email": "rhowardgaterp9@nyu.edu",
    "country": "Croatia",
    "postal_code": "10257",
    "favorite_color": "blue",
    "enrollment_date": "9/17/2021",
    "gpa": "2.37",
    "external_system": "internal"
  },
  {
    "student_id": "912",
    "first_name": "Clo",
    "last_name": "Blaber",
    "age": "19",
    "email": "cblaberpb@ycombinator.com",
    "country": "Bangladesh",
    "postal_code": "5110",
    "favorite_color": "green",
    "enrollment_date": "2/11/2022",
    "gpa": "3.3",
    "external_system": "internal"
  },
  {
    "student_id": "916",
    "first_name": "Minetta",
    "last_name": "Harvie",
    "age": "19",
    "email": "mharviepf@wp.com",
    "country": "United States",
    "postal_code": "23203",
    "favorite_color": "red",
    "enrollment_date": "2/16/2022",
    "gpa": "1.66",
    "external_system": "internal"
  },
  {
    "student_id": "923",
    "first_name": "Hollis",
    "last_name": "Shmyr",
    "age": "18",
    "email": "hshmyrpm@twitpic.com",
    "country": "Sweden",
    "postal_code": "441 28",
    "favorite_color": "green",
    "enrollment_date": "1/11/2022",
    "gpa": "1.1",
    "external_system": "internal"
  },
  {
    "student_id": "924",
    "first_name": "Gavrielle",
    "last_name": "Sproat",
    "age": "18",
    "email": "gsproatpn@yandex.ru",
    "country": "United States",
    "postal_code": "90094",
    "favorite_color": "green",
    "enrollment_date": "9/3/2021",
    "gpa": "0.83",
    "external_system": "internal"
  },
  {
    "student_id": "927",
    "first_name": "Editha",
    "last_name": "Surgison",
    "age": "25",
    "email": "esurgisonpq@trellian.com",
    "country": "United Kingdom",
    "postal_code": "IV1",
    "favorite_color": "blue",
    "enrollment_date": "5/15/2020",
    "gpa": "1.29",
    "external_system": "internal"
  },
  {
    "student_id": "933",
    "first_name": "Deeanne",
    "last_name": "Blinckhorne",
    "age": "25",
    "email": "dblinckhornepw@cloudflare.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "7/11/2022",
    "gpa": "0.18",
    "external_system": "internal"
  },
  {
    "student_id": "938",
    "first_name": "Antonino",
    "last_name": "Robbins",
    "age": "24",
    "email": "arobbinsq1@techcrunch.com",
    "country": "Egypt",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "10/9/2020",
    "gpa": "3.21",
    "external_system": "internal"
  },
  {
    "student_id": "939",
    "first_name": "Alfy",
    "last_name": "L' Estrange",
    "age": "24",
    "email": "alestrangeq2@ebay.co.uk",
    "country": "Iran",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "8/2/2022",
    "gpa": "1.84",
    "external_system": "internal"
  },
  {
    "student_id": "947",
    "first_name": "Roshelle",
    "last_name": "Fluger",
    "age": "24",
    "email": "rflugerqa@hexun.com",
    "country": "Mongolia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "6/23/2020",
    "gpa": "2.28",
    "external_system": "internal"
  },
  {
    "student_id": "950",
    "first_name": "Hurley",
    "last_name": "Bog",
    "age": "22",
    "email": "hbogqd@studiopress.com",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "7/10/2022",
    "gpa": "2.18",
    "external_system": "internal"
  },
  {
    "student_id": "951",
    "first_name": "Marlow",
    "last_name": "Jonke",
    "age": "20",
    "email": "mjonkeqe@army.mil",
    "country": "Indonesia",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "5/4/2020",
    "gpa": "1.98",
    "external_system": "internal"
  },
  {
    "student_id": "955",
    "first_name": "Kettie",
    "last_name": "O'Lynn",
    "age": "19",
    "email": "kolynnqi@eventbrite.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "2/16/2022",
    "gpa": "1.83",
    "external_system": "internal"
  },
  {
    "student_id": "956",
    "first_name": "Mano",
    "last_name": "Brisseau",
    "age": "19",
    "email": "mbrisseauqj@cargocollective.com",
    "country": "Ireland",
    "postal_code": "Y25",
    "favorite_color": "red",
    "enrollment_date": "6/6/2020",
    "gpa": "1.5",
    "external_system": "internal"
  },
  {
    "student_id": "957",
    "first_name": "Bert",
    "last_name": "Doughartie",
    "age": "24",
    "email": "bdoughartieqk@webmd.com",
    "country": "China",
    "postal_code": "",
    "favorite_color": "red",
    "enrollment_date": "3/2/2020",
    "gpa": "3.42",
    "external_system": "internal"
  },
  {
    "student_id": "958",
    "first_name": "Heath",
    "last_name": "Greenard",
    "age": "20",
    "email": "hgreenardql@craigslist.org",
    "country": "Russia",
    "postal_code": "353356",
    "favorite_color": "red",
    "enrollment_date": "2/25/2021",
    "gpa": "3.13",
    "external_system": "internal"
  },
  {
    "student_id": "961",
    "first_name": "Clementina",
    "last_name": "Lowle",
    "age": "24",
    "email": "clowleqo@yandex.ru",
    "country": "Iran",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "11/18/2021",
    "gpa": "0.69",
    "external_system": "internal"
  },
  {
    "student_id": "966",
    "first_name": "Iolanthe",
    "last_name": "Bunney",
    "age": "21",
    "email": "ibunneyqt@squidoo.com",
    "country": "Canada",
    "postal_code": "V9A",
    "favorite_color": "green",
    "enrollment_date": "6/3/2020",
    "gpa": "3.99",
    "external_system": "internal"
  },
  {
    "student_id": "967",
    "first_name": "Cleavland",
    "last_name": "Popescu",
    "age": "23",
    "email": "cpopescuqu@histats.com",
    "country": "Ukraine",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "11/18/2020",
    "gpa": "2.27",
    "external_system": "internal"
  },
  {
    "student_id": "970",
    "first_name": "Cher",
    "last_name": "Skellon",
    "age": "22",
    "email": "cskellonqx@buzzfeed.com",
    "country": "Norway",
    "postal_code": "1291",
    "favorite_color": "blue",
    "enrollment_date": "11/7/2022",
    "gpa": "3.68",
    "external_system": "internal"
  },
  {
    "student_id": "973",
    "first_name": "Shea",
    "last_name": "Megany",
    "age": "25",
    "email": "smeganyr0@yahoo.co.jp",
    "country": "Vietnam",
    "postal_code": "",
    "favorite_color": "blue",
    "enrollment_date": "6/7/2022",
    "gpa": "2.73",
    "external_system": "internal"
  },
  {
    "student_id": "976",
    "first_name": "Cinda",
    "last_name": "Lampl",
    "age": "22",
    "email": "clamplr3@admin.ch",
    "country": "Brazil",
    "postal_code": "13650-000",
    "favorite_color": "red",
    "enrollment_date": "8/25/2022",
    "gpa": "3.49",
    "external_system": "internal"
  },
  {
    "student_id": "983",
    "first_name": "Kendrick",
    "last_name": "Cornewell",
    "age": "21",
    "email": "kcornewellra@dailymotion.com",
    "country": "Portugal",
    "postal_code": "4845-028",
    "favorite_color": "blue",
    "enrollment_date": "11/18/2020",
    "gpa": "2.2",
    "external_system": "internal"
  },
  {
    "student_id": "987",
    "first_name": "Crichton",
    "last_name": "Skrines",
    "age": "21",
    "email": "cskrinesre@google.de",
    "country": "Tanzania",
    "postal_code": "",
    "favorite_color": "green",
    "enrollment_date": "9/17/2022",
    "gpa": "2.13",
    "external_system": "internal"
  },
  {
    "student_id": "988",
    "first_name": "Edwina",
    "last_name": "Partrick",
    "age": "21",
    "email": "epartrickrf@loc.gov",
    "country": "Poland",
    "postal_code": "14-420",
    "favorite_color": "green",
    "enrollment_date": "7/8/2020",
    "gpa": "2.24",
    "external_system": "internal"
  },
  {
    "student_id": "994",
    "first_name": "Bryana",
    "last_name": "Brittan",
    "age": "23",
    "email": "bbrittanrl@1688.com",
    "country": "Mexico",
    "postal_code": "92015",
    "favorite_color": "blue",
    "enrollment_date": "2/3/2021",
    "gpa": "0.89",
    "external_system": "internal"
  },
  {
    "student_id": "997",
    "first_name": "Lanie",
    "last_name": "Claesens",
    "age": "18",
    "email": "lclaesensro@google.de",
    "country": "Brazil",
    "postal_code": "75600-000",
    "favorite_color": "blue",
    "enrollment_date": "12/25/2022",
    "gpa": "0.06",
    "external_system": "internal"
  },
  {
    "student_id": "998",
    "first_name": "Danette",
    "last_name": "Mortel",
    "age": "19",
    "email": "dmortelrp@unicef.org",
    "country": "Poland",
    "postal_code": "37-754",
    "favorite_color": "red",
    "enrollment_date": "10/13/2020",
    "gpa": "1.76",
    "external_system": "internal"
  }
]